/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.webp;

public class libwebpJNI {
  public final static native int WebPGetDecoderVersion();
  public final static native int WebPGetInfo(byte[] jarg1, long jarg2, int[] jarg3, int[] jarg4);
  public final static native byte[] WebPDecodeRGB(byte[] jarg1, long jarg2, int[] jarg3, int[] jarg4);
  public final static native byte[] WebPDecodeRGBA(byte[] jarg1, long jarg2, int[] jarg3, int[] jarg4);
  public final static native byte[] WebPDecodeARGB(byte[] jarg1, long jarg2, int[] jarg3, int[] jarg4);
  public final static native byte[] WebPDecodeBGR(byte[] jarg1, long jarg2, int[] jarg3, int[] jarg4);
  public final static native byte[] WebPDecodeBGRA(byte[] jarg1, long jarg2, int[] jarg3, int[] jarg4);
}
